Slent fixm 244
fixm-ccb/fixm-user-manual-4.3.0-testing pull request #2
Opened 2023-03-07 17:01 UTC by slent-ctr

In /docs/general-guidance/rules-for-absent-data.md:

I made minor edits to the text regarding the support for nillable elements in version 4.2.0, but did NOT update '4.2.0' to '4.3.0' since these changes were made in 4.2.0 and since then the support for nillable elements is more or less steady state. Perhaps this language should be removed?

---------------------------------------------------

IN /docs/how-to-create-application/initial-download-and-setup.md:

In step one of the instructions, I updated the link to point to the download page (https://fixm.aero/release.html?rel=Basic-Msg-1.1.0&ret=app), rather than directly to the .zip file.

2023-03-09 16:37 UTC, cmcgowan-CTR approved these changes

2023-03-20 16:45 UTC, CPiroli-CTR requested changes
There was talk about whether we wanted to leave the "How To" sections working with older versions of FIXM (since the version is irrelevant to the lessons being taught) or whether we wanted to update them to the latest version.  This change updates this "How To" to the latest version but doesn't change the instructions so that it matches how to build the schemas with the changes present in the latest version.  We should either revert this change (if we aren't going to update these sections) or fix it to work for 4.3.0 (which modified the schema build path).

2023-03-20 16:59 UTC, CPiroli-CTR reviewed
Not sure I oppose removing the pre-filled selections.  Just wanted to highlight the change to make sure we don't want these anymore.

2023-03-20 17:08 UTC, CPiroli-CTR reviewed
Same comment on "How To" sections.

2023-03-20 17:14 UTC, CPiroli-CTR reviewed
Link and test don't agree (text should be updated to 1.1.0) for FF-ICE Message change.

2023-03-22 19:57 UTC, CPiroli-CTR commented on docs/home.md
> +[SUBMIT CONTENT]: https://fixm.aero/contact.pl
Are we sure we want to remove all the preset values?

2023-03-23 15:54 UTC, merged