Slent fixm 229
fixm-ccb/fixm-user-manual-4.3.0-testing pull request #9
Opened 2023-03-27 17:51 UTC by slent-ctr

In addition to adding the page regarding non-aerodrome departures and air files, this pull request also includes an unrelated change to geographical-positions.md. There were a couple of references to 4.2 that I believe should be changed to 4.3.

With respect to the main issue, the page regarding non-aerodrome departures and air files, please closely scrutinize the XML examples. I created them by hand, and, believe it or not, I'm WAY more familiar with the .xsd formatting than I am with actual XML that uses a .xsd.

2023-03-30 13:47 UTC, cmcgowan-CTR requested changes
Not sure if the spelling of "air file" is correct or if it should be "airfile" or if it really matters?
Maybe we use "flights filed from the air" instead to avoid this question.

2023-03-31 16:16 UTC, cmcgowan-CTR approved these changes

2023-04-06 17:17 UTC, CPiroli-CTR approved these changes
Made a number of edits including moving the file in sidebar and various changes to the page itself.  Please review changes and see if you agree.

2023-04-13 13:44 UTC, cmcgowan-CTR approved these changes

2023-05-04 18:57 UTC, merged